## Loading all the libraries needed

In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series, read_csv
import matplotlib.pyplot as plt
import matplotlib 
import re
import itertools

# Enable inline plotting
%matplotlib inline

### Loading File

In [2]:
location = r'high-protien-food-aggregation2.csv'
df = pd.read_csv(location)

### Cleaning out empty rows and colums
manually updated the spreadsheet from my previous project adding categories, this helps with the grouping and aggregation. Makes informations more clear

In [3]:
df = df.dropna()
df = df.dropna(axis=1)
df

,Category,Food (Per 100g),Protein,Carbs g,Fat g,Calories (kcal)
0,Fruits,Almond Nuts,21.10,6.90,55.800,614
1,Vegetable,Anchovies,14.50,0.10,2.800,85
2,Vegetable,Asparagus,2.90,2.00,0.600,25
3,Fruits,Avocado,1.90,1.90,19.500,195
5,Vegetable,Baked Beans,9.50,22.10,0.400,130
6,Fruits,Bananas,1.20,23.20,0.300,100
7,Meat,Beef Fillet Steak,20.90,0.00,7.900,155
8,Grains,Bread (wholemeal),11.00,39.10,2.200,220
9,Vegetable,Broccoli,4.20,3.20,0.200,31
10,Vegetable,Carrots,0.60,7.90,0.300,37
11,Dairy,Cheese,30.90,0.10,15.000,260
12,Meat,Chicken Breast (Skinless),23.50,0.00,1.700,109
13,Fruits,Coconut,3.33,15.23,33.490,354
14,Meat,Cod fish,17.90,0.00,0.900,80
15,Dairy,Cottage Cheese,12.20,4.50,1.500,80
16,Grains,Couscous,15.10,73.10,1.100,365
19,Fruits,Goji Berries,12.30,57.70,0.300,285
20,Meat,Haddock Fish,16.40,0.00,1.200,80
21,Other,Hummus,7.40,9.80,26.800,310
22,Meat,Lamb (Steak),19.90,0.80,3.200,115
23,Meat,Lobster,26.41,3.12,1.940,143
24,Dairy,Milk (Semi Skimmed),3.60,4.80,1.800,50
25,Dairy,Milk (Whole),3.30,4.70,3.600,64
27,Fruits,Orange,1.10,8.50,0.100,39
28,Meat,Orange Roughy Fish,22.64,0.00,0.034,105
29,Grains,Pasta,12.50,73.00,1.400,355
30,Other,Peanut Butter (Crunchy),24.90,10.10,50.200,586
31,Vegetable,Peas,5.90,9.00,0.900,70
32,Other,Pizza (Pepperoni),11.40,28.00,11.100,260
34,Grains,Porridge oats,11.00,60.00,8.000,356
35,Vegetable,Potatoes,2.10,17.20,0.200,80
36,Meat,Prawns,17.00,0.30,0.900,80
37,Vegetable,Pumpkin Seeds,28.80,15.20,45.600,586
38,Grains,Rice (brown),6.90,74.00,2.800,350
39,Meat,Salmon Fish Fillets (Boneless),21.60,0.00,14.000,215
41,Meat,Sausages (pork),13.90,11.90,17.000,255
42,Vegetable,soya beans,35.90,14.80,18.600,375
43,Grains,Spaghetti,5.10,33.00,1.300,165
44,Vegetable,Spinach,2.80,1.50,0.800,24
45,Fruits,Sunflower Seeds,23.40,18.60,47.500,600
47,Meat,Tilapia Fish,24.00,0.00,4.000,105
48,Other,Tofu,12.10,0.60,6.000,105
49,Meat,Tuna Fish (Steak),25.60,0.00,0.500,110
50,Meat,Tuna Fish (Tinned),26.30,0.00,10.700,202
51,Meat,Turkey Breast (Skinless),22.30,0.00,1.200,100
53,Other,Yogurt,4.50,6.60,11.000,145

In [4]:
df.dtypes

Category            object
Food (Per 100g)     object
Protein            float64
Carbs g            float64
Fat g              float64
Calories (kcal)    float64
dtype: object

## # Grouping Data
First finding means of data by category then breaking down data into groups using two axes

In [5]:
grouped =df[['Protein', 'Carbs g', 'Fat g', 'Calories (kcal)']].groupby(df['Category'])
grouped

In [6]:
grouped.mean()

             Protein    Carbs g      Fat g  Calories (kcal)
Category
Dairy      12.500000   3.525000   5.475000       113.500000
Fruits      9.190000  18.861429  22.427143       312.428571
Grains     10.266667  58.700000   2.800000       301.833333
Meat       21.310714   1.151429   4.655286       132.428571
Other      12.060000  11.020000  21.020000       281.200000
Vegetable  10.720000   9.300000   7.040000       144.300000

In [7]:
means =df['Protein'].groupby([df['Category'], df['Food (Per 100g)']]).mean()
means

Category   Food (Per 100g)
Dairy      Cheese                            30.90
           Cottage Cheese                    12.20
           Milk (Semi Skimmed)                3.60
           Milk (Whole)                       3.30
Fruits     Almond Nuts                       21.10
           Avocado                            1.90
           Bananas                            1.20
           Coconut                            3.33
           Goji Berries                      12.30
           Orange                             1.10
           Sunflower Seeds                   23.40
Grains     Bread (wholemeal)                 11.00
           Couscous                          15.10
           Pasta                             12.50
           Porridge oats                     11.00
           Rice (brown)                       6.90
           Spaghetti                          5.10
Meat       Beef Fillet Steak                 20.90
           Chicken Breast (Skinless)         23.50
           Cod fish                          17.90
           Haddock Fish                      16.40
           Lamb (Steak)                      19.90
           Lobster                           26.41
           Orange Roughy Fish                22.64
           Prawns                            17.00
           Salmon Fish Fillets (Boneless)    21.60
           Sausages (pork)                   13.90
           Tilapia Fish                      24.00
           Tuna Fish (Steak)                 25.60
           Tuna Fish (Tinned)                26.30
           Turkey Breast (Skinless)          22.30
Other      Hummus                             7.40
           Peanut Butter (Crunchy)           24.90
           Pizza (Pepperoni)                 11.40
           Tofu                              12.10
           Yogurt                             4.50
Vegetable  Anchovies                         14.50
           Asparagus                          2.90
           Baked Beans                        9.50
           Broccoli                           4.20
           Carrots                            0.60
           Peas                               5.90
           Potatoes                           2.10
           Pumpkin Seeds                     28.80
           Spinach                            2.80
           soya beans                        35.90
Name: Protein, dtype: float64

In [8]:
def peak_to_peak(arr):
    return arr.max() - arr.min()
grouped.agg(peak_to_peak)

           Protein  Carbs g   Fat g  Calories (kcal)
Category
Dairy        27.60      4.7  13.500              210
Fruits       22.30     55.8  55.700              575
Grains       10.00     41.0   6.900              200
Meat         12.51     11.9  16.966              175
Other        20.40     27.4  44.200              481
Vegetable    35.30     22.0  45.400              562

In [9]:
grouped.describe()

                   Protein    Carbs g      Fat g  Calories (kcal)
Category
Dairy     count   4.000000   4.000000   4.000000         4.000000
          mean   12.500000   3.525000   5.475000       113.500000
          std    12.942179   2.286737   6.417359        98.432718
          min     3.300000   0.100000   1.500000        50.000000
          25%     3.525000   3.400000   1.725000        60.500000
          50%     7.900000   4.600000   2.700000        72.000000
          75%    16.875000   4.725000   6.450000       125.000000
          max    30.900000   4.800000  15.000000       260.000000
Fruits    count   7.000000   7.000000   7.000000         7.000000
          mean    9.190000  18.861429  22.427143       312.428571
          std     9.748643  18.612892  23.632862       227.230322
          min     1.100000   1.900000   0.100000        39.000000
          25%     1.550000   7.700000   0.300000       147.500000
          50%     3.330000  15.230000  19.500000       285.000000
          75%    16.700000  20.900000  40.495000       477.000000
          max    23.400000  57.700000  55.800000       614.000000
Grains    count   6.000000   6.000000   6.000000         6.000000
          mean   10.266667  58.700000   2.800000       301.833333
          std     3.672964  18.397174   2.626785        86.591955
          min     5.100000  33.000000   1.100000       165.000000
          25%     7.925000  44.325000   1.325000       252.500000
          50%    11.000000  66.500000   1.800000       352.500000
          75%    12.125000  73.075000   2.650000       355.750000
          max    15.100000  74.000000   8.000000       365.000000
Meat      count  14.000000  14.000000  14.000000        14.000000
          mean   21.310714   1.151429   4.655286       132.428571
          std     3.878502   3.204725   5.520181        55.095322
          min    13.900000   0.000000   0.034000        80.000000
          25%    18.400000   0.000000   0.975000       101.250000
          50%    21.950000   0.000000   1.820000       109.500000
          75%    23.875000   0.225000   6.925000       152.000000
          max    26.410000  11.900000  17.000000       255.000000
Other     count   5.000000   5.000000   5.000000         5.000000
          mean   12.060000  11.020000  21.020000       281.200000
          std     7.813002  10.231911  18.092042       189.590875
          min     4.500000   0.600000   6.000000       105.000000
          25%     7.400000   6.600000  11.000000       145.000000
          50%    11.400000   9.800000  11.100000       260.000000
          75%    12.100000  10.100000  26.800000       310.000000
          max    24.900000  28.000000  50.200000       586.000000
Vegetable count  10.000000  10.000000  10.000000        10.000000
          mean   10.720000   9.300000   7.040000       144.300000
          std    12.215819   7.669130  14.680615       187.009239
          min     0.600000   0.100000   0.200000        24.000000
          25%     2.825000   2.300000   0.325000        32.500000
          50%     5.050000   8.450000   0.700000        75.000000
          75%    13.250000  15.100000   2.325000       118.750000
          max    35.900000  22.100000  45.600000       586.000000

In [10]:
list(df)

['Category',
 'Food (Per 100g)',
 'Protein',
 'Carbs g',
 'Fat g',
 'Calories (kcal)']

### Converting Macro 
the grams to calories using the following
Protien = 4cal per gram
Carb = 4cal per gram
Fat = 9cal per gram

In [11]:
ProteinCal = df['Protein'] * 4
CarbsCal = df['Carbs g'] * 4
FatCal = df['Fat g'] * 9

ProteinRatio = df['Calories (kcal)'] / ProteinCal
CarbsRatio = df['Calories (kcal)'] / CarbsCal  #will not use for this assignment
FatsRatio = df['Calories (kcal)'] / FatCal  #will not use for this assignment

In [12]:
df["Protein Ratio"] = ProteinRatio

In [13]:
df

,Category,Food (Per 100g),Protein,Carbs g,Fat g,Calories (kcal),Protein Ratio
0,Fruits,Almond Nuts,21.10,6.90,55.800,614,7.274882
1,Vegetable,Anchovies,14.50,0.10,2.800,85,1.465517
2,Vegetable,Asparagus,2.90,2.00,0.600,25,2.155172
3,Fruits,Avocado,1.90,1.90,19.500,195,25.657895
5,Vegetable,Baked Beans,9.50,22.10,0.400,130,3.421053
6,Fruits,Bananas,1.20,23.20,0.300,100,20.833333
7,Meat,Beef Fillet Steak,20.90,0.00,7.900,155,1.854067
8,Grains,Bread (wholemeal),11.00,39.10,2.200,220,5.000000
9,Vegetable,Broccoli,4.20,3.20,0.200,31,1.845238
10,Vegetable,Carrots,0.60,7.90,0.300,37,15.416667
11,Dairy,Cheese,30.90,0.10,15.000,260,2.103560
12,Meat,Chicken Breast (Skinless),23.50,0.00,1.700,109,1.159574
13,Fruits,Coconut,3.33,15.23,33.490,354,26.576577
14,Meat,Cod fish,17.90,0.00,0.900,80,1.117318
15,Dairy,Cottage Cheese,12.20,4.50,1.500,80,1.639344
16,Grains,Couscous,15.10,73.10,1.100,365,6.043046
19,Fruits,Goji Berries,12.30,57.70,0.300,285,5.792683
20,Meat,Haddock Fish,16.40,0.00,1.200,80,1.219512
21,Other,Hummus,7.40,9.80,26.800,310,10.472973
22,Meat,Lamb (Steak),19.90,0.80,3.200,115,1.444724
23,Meat,Lobster,26.41,3.12,1.940,143,1.353654
24,Dairy,Milk (Semi Skimmed),3.60,4.80,1.800,50,3.472222
25,Dairy,Milk (Whole),3.30,4.70,3.600,64,4.848485
27,Fruits,Orange,1.10,8.50,0.100,39,8.863636
28,Meat,Orange Roughy Fish,22.64,0.00,0.034,105,1.159452
29,Grains,Pasta,12.50,73.00,1.400,355,7.100000
30,Other,Peanut Butter (Crunchy),24.90,10.10,50.200,586,5.883534
31,Vegetable,Peas,5.90,9.00,0.900,70,2.966102
32,Other,Pizza (Pepperoni),11.40,28.00,11.100,260,5.701754
34,Grains,Porridge oats,11.00,60.00,8.000,356,8.090909
35,Vegetable,Potatoes,2.10,17.20,0.200,80,9.523810
36,Meat,Prawns,17.00,0.30,0.900,80,1.176471
37,Vegetable,Pumpkin Seeds,28.80,15.20,45.600,586,5.086806
38,Grains,Rice (brown),6.90,74.00,2.800,350,12.681159
39,Meat,Salmon Fish Fillets (Boneless),21.60,0.00,14.000,215,2.488426
41,Meat,Sausages (pork),13.90,11.90,17.000,255,4.586331
42,Vegetable,soya beans,35.90,14.80,18.600,375,2.611421
43,Grains,Spaghetti,5.10,33.00,1.300,165,8.088235
44,Vegetable,Spinach,2.80,1.50,0.800,24,2.142857
45,Fruits,Sunflower Seeds,23.40,18.60,47.500,600,6.410256
47,Meat,Tilapia Fish,24.00,0.00,4.000,105,1.093750
48,Other,Tofu,12.10,0.60,6.000,105,2.169421
49,Meat,Tuna Fish (Steak),25.60,0.00,0.500,110,1.074219
50,Meat,Tuna Fish (Tinned),26.30,0.00,10.700,202,1.920152
51,Meat,Turkey Breast (Skinless),22.30,0.00,1.200,100,1.121076
53,Other,Yogurt,4.50,6.60,11.000,145,8.055556

### Quality Protien Source
This is the step to where I will print out the rows that have good protien ratio. Protein ratio with value less than 2 means you have more protien per overall calories.

In [14]:
print (df.loc[df['Protein Ratio'] < 2 ])

     Category            Food (Per 100g)  Protein  Carbs g   Fat g  \
1   Vegetable                  Anchovies    14.50     0.10   2.800
7        Meat          Beef Fillet Steak    20.90     0.00   7.900
9   Vegetable                   Broccoli     4.20     3.20   0.200
12       Meat  Chicken Breast (Skinless)    23.50     0.00   1.700
14       Meat                   Cod fish    17.90     0.00   0.900
15      Dairy             Cottage Cheese    12.20     4.50   1.500
20       Meat               Haddock Fish    16.40     0.00   1.200
22       Meat               Lamb (Steak)    19.90     0.80   3.200
23       Meat                    Lobster    26.41     3.12   1.940
28       Meat         Orange Roughy Fish    22.64     0.00   0.034
36       Meat                     Prawns    17.00     0.30   0.900
47       Meat               Tilapia Fish    24.00     0.00   4.000
49       Meat          Tuna Fish (Steak)    25.60     0.00   0.500
50       Meat         Tuna Fish (Tinned)    26.30     0.00  10.700
51       Meat   Turkey Breast (Skinless)    22.30     0.00   1.200

    Calories (kcal)  Protein Ratio
1                85       1.465517
7               155       1.854067
9                31       1.845238
12              109       1.159574
14               80       1.117318
15               80       1.639344
20               80       1.219512
22              115       1.444724
23              143       1.353654
28              105       1.159452
36               80       1.176471
47              105       1.093750
49              110       1.074219
50              202       1.920152
51              100       1.121076